services:
  db:
    image: postgres:16
    container_name: taskflow-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
      POSTGRES_DB: taskflow
    volumes:
      - taskflow-db-data:/var/lib/postgresql/data

volumes:
  taskflow-db-data:
